#! /bin/bash

if [ "$#" -gt 1 ] || echo "$1" |grep -q "[^0-9]" || [ "$1" -gt 100 ];then
	echo "Please enter ONE integer (0-100) "
	exit 1
fi 2> /dev/null

VAR=${1:-90}

df | awk '{print $5,$6}' | awk -v AWK_VAR="$VAR" -F "%" '{if($1>=AWK_VAR){print $1"%",$2}}'  

